=== Gsqr/bet-wizard/src/main/resources/schema/event.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "description": "Contains information related to an event from Sportsbook",
  "properties": {
    "eventId": {
      "description": "Sportsbook event id",
      "type": "integer",
      "existingJavaType": "Long",
      "format": "int64"
    },
    "eventName":{
      "description": "Name of the event stored in Sportsbook",
      "type": "string"
    },
    "eventGroupId": {
      "description": "The group this event belongs to. This is usually a league or tournament but can be anything defined by the traders.",
      "type": "integer",
      "existingJavaType": "Long",
      "format": "int64"
    },
    "eventTreePath": {
      "description": "Ordered list representing the tree path (hierarchy) from Sportsbook",
      "type": "array",
      "items": {
        "$ref": "eventGroup.json"
      }
    },
    "startDate": {
      "description": "The user defined event start date",
      "type": "string",
      "format": "date-time"
    },
    "settledDate": {
      "description": "The date when all betoffers on the event are settled",
      "type": "string",
      "format": "date-time"
    },
    "sportId": {
      "description": "Sport identifier, like FOOTBALL",
      "type": "string"
    }
  },
  "required": [
    "eventId"
  ]
}

=== Gsqr/bet-wizard/src/main/resources/events.json
[
  {
    "eventId": 1000000001,
    "eventName": "Bournemouth-Newcastle United",
    "eventGroupId": 1000000001,
    "eventTreePath": [
      {
        "eventGroupId": 1000000001,
        "eventGroupName": "Premier League"
      }
    ],
    "startDate": "2019-03-15T11:14:58.877+0000",
    "settledDate": "2019-03-15T08:14:58.878+0000",
    "sportId": "Football"
  },
  {
    "eventId": 1000000002,
    "eventName": "Burnley-Leicester City",
    "eventGroupId": 1000000001,
    "eventTreePath": [
      {
        "eventGroupId": 1000000001,
        "eventGroupName": "Premier League"
      }
    ],
    "startDate": "2019-03-15T11:14:58.878+0000",
    "settledDate": "2019-03-15T08:14:58.878+0000",
    "sportId": "Football"
  },
  {
    "eventId": 1000000003,
    "eventName": "West Ham-Huddersfield Town",
    "eventGroupId": 1000000001,
    "eventTreePath": [
      {
        "eventGroupId": 1000000001,
        "eventGroupName": "Premier League"
      }
    ],
    "startDate": "2019-03-15T11:14:58.878+0000",
    "settledDate": "2019-03-15T08:14:58.878+0000",
    "sportId": "Football"
  },
  {
    "eventId": 1000000004,
    "eventName": "Fulham-Liverpool",
    "eventGroupId": 1000000001,
    "eventTreePath": [
      {
        "eventGroupId": 1000000001,
        "eventGroupName": "Premier League"
      }
    ],
    "startDate": "2019-03-15T11:14:58.878+0000",
    "settledDate": "2019-03-15T08:14:58.878+0000",
    "sportId": "Football"
  },
  {
    "eventId": 1000000005,
    "eventName": "Everton-Chelsea",
    "eventGroupId": 1000000001,
    "eventTreePath": [
      {
        "eventGroupId": 1000000001,
        "eventGroupName": "Premier League"
      }
    ],
    "startDate": "2019-03-15T11:14:58.878+0000",
    "settledDate": "2019-03-15T08:14:58.878+0000",
    "sportId": "Football"
  }
]

=== Gsqr/bet-wizard/event.json
{
  "eventId": 11111,
  "eventName": "EVENNAME",
  "eventGroupId": 2222288,
  "eventTreePath": [
    {
      "eventGroupId": 2222288,
      "eventGroupName": "EVENTGROUPNAME"
    }
  ],
  "startDate": "2019-03-13T18:45:13.875+0000",
  "settledDate": "2019-03-13T18:45:13.875+0000",
  "sportId": "SPORTID"
}

=== Gsqr/bet-wizard/events.json
[{"eventId":1000000001,"eventName":"EventName0","eventGroupId":1000000001,"eventTreePath":[{"eventGroupId":1000000001,"eventGroupName":"Premier League"}],"startDate":"2019-03-14T08:49:54.635+0000","settledDate":"2019-03-14T08:49:54.635+0000","sportId":"Football"},{"eventId":1000000002,"eventName":"EventName1","eventGroupId":1000000001,"eventTreePath":[{"eventGroupId":1000000001,"eventGroupName":"Premier League"}],"startDate":"2019-03-14T08:49:54.635+0000","settledDate":"2019-03-14T08:49:54.635+0000","sportId":"Football"},{"eventId":1000000003,"eventName":"EventName2","eventGroupId":1000000001,"eventTreePath":[{"eventGroupId":1000000001,"eventGroupName":"Premier League"}],"startDate":"2019-03-14T08:49:54.635+0000","settledDate":"2019-03-14T08:49:54.635+0000","sportId":"Football"},{"eventId":1000000004,"eventName":"EventName3","eventGroupId":1000000001,"eventTreePath":[{"eventGroupId":1000000001,"eventGroupName":"Premier League"}],"startDate":"2019-03-14T08:49:54.635+0000","settledDate":"2019-03-14T08:49:54.635+0000","sportId":"Football"},{"eventId":1000000005,"eventName":"EventName4","eventGroupId":1000000001,"eventTreePath":[{"eventGroupId":1000000001,"eventGroupName":"Premier League"}],"startDate":"2019-03-14T08:49:54.635+0000","settledDate":"2019-03-14T08:49:54.635+0000","sportId":"Football"}]
